/**
 * Content Script <-> Background <-> Popup 間のメッセージタイプ定義
 */

// Background -> Content
export const MESSAGE_TYPES = {
  // ログ関連
  LOG_CAPTURED: 'LOG_CAPTURED',
  GET_LOGS: 'GET_LOGS',
  CLEAR_LOGS: 'CLEAR_LOGS',
  EXPORT_LOGS: 'EXPORT_LOGS',
  SEARCH_LOGS: 'SEARCH_LOGS',
  
  // パフォーマンス関連
  PERFORMANCE_CAPTURED: 'PERFORMANCE_CAPTURED',
  GET_PERFORMANCE_DATA: 'GET_PERFORMANCE_DATA',
  CLEAR_PERFORMANCE_DATA: 'CLEAR_PERFORMANCE_DATA',
  
  // スニペット関連
  GET_SNIPPETS: 'GET_SNIPPETS',
  SAVE_SNIPPET: 'SAVE_SNIPPET',
  DELETE_SNIPPET: 'DELETE_SNIPPET',
  UPDATE_SNIPPET: 'UPDATE_SNIPPET',
  IMPORT_SNIPPETS: 'IMPORT_SNIPPETS',
  EXPORT_SNIPPETS: 'EXPORT_SNIPPETS',
  
  // クエリビルダー関連
  GET_TABLES: 'GET_TABLES',
  GET_FIELDS: 'GET_FIELDS',
  EXECUTE_QUERY: 'EXECUTE_QUERY',
  
  // 設定関連
  GET_SETTINGS: 'GET_SETTINGS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  
  // インスタンス情報
  GET_INSTANCE_INFO: 'GET_INSTANCE_INFO',
  
  // Content Script操作
  INSERT_CODE: 'INSERT_CODE',
  EXECUTE_GLIDERECORD_QUERY: 'EXECUTE_GLIDERECORD_QUERY',
  
  // 拡張機能制御
  ENABLE_DEBUGGER: 'ENABLE_DEBUGGER',
  DISABLE_DEBUGGER: 'DISABLE_DEBUGGER',
  GET_STATUS: 'GET_STATUS',
};

// レスポンスタイプ
export const RESPONSE_TYPES = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  PARTIAL: 'PARTIAL',
};

// エラーコード
export const ERROR_CODES = {
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  STORAGE_ERROR: 'STORAGE_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  INVALID_REQUEST: 'INVALID_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  SERVICENOW_ERROR: 'SERVICENOW_ERROR',
};